apiVersion: apps/v1
kind: Deployment
metadata:
  name: peercode-react
  labels:
    app: peercode-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peercode-react
  template:
    metadata:
      labels:
        app: peercode-react
    spec:
      containers:
        - name: peercode-react
          image: public.ecr.aws/a6n0p1z7/g55-peercode:${SHA}-peercode-react
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: config
                key: NODE_ENV
          - name: REACT_APP_MATCHMAKING_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: config
                key: REACT_APP_MATCHMAKING_TIMEOUT
          - name: REACT_APP_FIREBASE_API_KEY
            valueFrom:
              secretKeyRef:
                name: secret
                key: REACT_APP_FIREBASE_API_KEY
          - name: REACT_APP_FIREBASE_AUTH_DOMAIN
            valueFrom:
              secretKeyRef:
                name: secret
                key: REACT_APP_FIREBASE_AUTH_DOMAIN
          - name: REACT_APP_FIREBASE_PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: secret
                key: REACT_APP_FIREBASE_PROJECT_ID
          - name: REACT_APP_FIREBASE_STORAGE_BUCKET
            valueFrom:
              secretKeyRef:
                name: secret
                key: REACT_APP_FIREBASE_STORAGE_BUCKET
          - name: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
            valueFrom:
              secretKeyRef:
                name: secret
                key: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
          - name: REACT_APP_FIREBASE_APP_ID
            valueFrom:
              secretKeyRef:
                name: secret
                key: REACT_APP_FIREBASE_APP_ID
          - name: REACT_APP_FIREBASE_MEASUREMENT_ID
            valueFrom:
              secretKeyRef:
                name: secret
                key: REACT_APP_FIREBASE_MEASUREMENT_ID
---
apiVersion: v1
kind: Service
metadata:
  name: peercode-react
spec:
  type: LoadBalancer
  selector:
    app: peercode-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
